version: 2

sources:
    - name: coffee_shop
      description: '{{ doc("project_description") }}'
      project: analytics-engineers-club
      freshness:
        error_after:
          count: 12
          period: hour
      loaded_at_field: created_at  
      tables:
        - name: customers
          description: details about customers that have visited the coffee shop
          columns:
            - name: id
              tests:
                - unique
                - not_null

        - name: orders
          description: details about each order a customer made at the coffee shop 
          columns:
            - name: id
              tests:
                - unique
                - not_null